use_frameworks!

platform :ios, '9.0'

source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'LZCamera_Example' do
  pod 'LZCamera', :path => '../'
  target 'LZCamera_Tests' do
    inherit! :search_paths

	#pod 'FBSnapshotTestCase'
  end
end
